.PHONY: clean

p36: image_conversion.h image_conversion-utils.c p36.c
	clang -Wall -o p36 image_conversion-utils.c p36.c -lm

p63: image_conversion.h image_conversion-utils.c p63.c
	clang -Wall -o p63 image_conversion-utils.c p63.c -lm